### ISSUE TITLE
Collect examples from issues

### ISSUE THREAD

**Issue by jessehouwing** [tfsaggregator/tfsaggregator#101]
It'd be great if we could collect some of the examples we've given as answers to issues. I started with the Open/Close example, though I still need to validate it on the server to see if it causes any issues. Since it's a recursive rule, it's hard to test in the unit tests.

 * [x] https://github.com/tfsaggregator/tfsaggregator/wiki/Auto-Open-Auto-Close
 * [x] Assign to a user (use the display name) https://github.com/tfsaggregator/tfsaggregator/issues/97
 * [x] Auto-create children: https://github.com/tfsaggregator/tfsaggregator/issues/89
 * [x] Recursive sum of value to parent: https://github.com/tfsaggregator/tfsaggregator/issues/63

**Comment by jessehouwing** [comment]
2 and 3 were already listed in other example pages
